### ISSUE TITLE
Trailing whitespace in login email is rejected

### ISSUE THREAD

**Issue by JoshuaRLi** [standardnotes/android-classic#123]
I was trying to login on the android app today, and noticed that trailing whitespace in the email is not stripped before authentication.

I'm using an autocomplete keyboard with automatic spacing/grammar correction (and I'm sure a lot of other mobile users use similar keyboards), and that's what appended a trailing space without my immediate knowledge, leading to multiple rejected login attempts before I realized what was going on.

I don't know any Kotlin, so I'm opening an issue instead. The fix should be trivial. Thanks!

**Comment by deftelf** [comment]
Agreed, though I need to check that that space is ignored by the server on signup (I really hope it is!) @mobitar ? Either way it probably makes sense to strip it.

Incidentally, this is a workaround for the keyboard bug, the text box inputType is set to email, so the keyboard really really shouldn't add spaces.

**Comment by mobitar** [comment]
No nothing is cleaned server side. This is a client-centric system ;) We should have set some ground rules in the beginning as to how client input should be cleaned. It's tricky to do now because if you force something then old users are affected.

So we need to figure out a smooth transition plan.

**Comment by JoshuaRLi** [comment]
@deftelf I'm using the [Fleksy](http://fleksy.com/) keyboard, if you were wondering. It automatically added a trailing space when I did a dictionary suggestion (I have something like em mapped to my email).
