### ISSUE TITLE
Material Design app icon

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/android-classic#67]
From what I can see, the app is currently using the same icon as the desktop app. Google has provided documentation regarding app icons that fit in with [Material Design](https://material.io/guidelines/style/icons.html#icons-product-icons).

If it is okay with y'all then can I contact an icon pack developer and see if a new icon can be created? It would simply be a Material Design version of the current icon, not a total redesign so the icon will remain consistent across platforms.

**Comment by deftelf** [comment]
I'm happy for this, though the branding is probably more up to @mobitar

**Comment by Lokesh-Krishna** [comment]
In that case I'll wait until @mobitar gives me an all clear before contacting an icon designer :)

**Comment by mobitar** [comment]
You want us to hire an icon designer?

**Comment by Lokesh-Krishna** [comment]
[Alexey](https://github.com/varlesh) is an icon designer who makes open source icon packs for GNU/Linux distributions. He helped out Wallabag (an open source read-it-later app) in the past by designing a Material Design icon for their Android app so I think he might be able to help here as well.

Would that qualify as hiring? All that we would need to do is credit him as the designer of the icon.

**Comment by mobitar** [comment]
Yes that's fine.

**Comment by Lokesh-Krishna** [comment]
Are there any icon resources that I can link them to?
